import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Providers } from '@/providers/next-ui';


const inter = Inter( { subsets: [ "latin" ] } );


export const metadata: Metadata = {
  title: "NextUI Template",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {

  return (
    <html lang="en" className='dark'>
      <body className={ inter.className }>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  );
}
